[project]
name = "robotics-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.12.0",
    "flake8>=7.3.0",
    "mujoco>=3.4.0",
    "numpy>=2.3.5",
    "pytest>=9.0.2",
    "pytest-xdist>=3.8.0",
]
